name: enough_mail
description: IMAP, POP3 and SMTP for email developers. Choose between a low level and a high level API for mailing. Parse and generate MIME messages. Discover email settings.
version: 1.2.2
homepage: https://github.com/Enough-Software/enough_mail

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  pedantic: ^1.11.0
  event_bus: ^2.0.0
  crypto: ^3.0.1
  encrypt: ^5.0.0
  pointycastle: ^3.0.1
  basic_utils: ^3.0.2
  xml: ^5.1.0
  intl: ^0.17.0
  enough_serialization: ^1.4.0
    #path: ../enough_serialization
  enough_convert: ^1.3.0
    # path: ../enough_convert
  collection: ^1.15.0



dev_dependencies:
  test: ^1.17.3

