name: enough_mail
description: IMAP, POP3 and SMTP email clients in pure Dart. Choose between a low level and a high level API for mailing.
version: 0.0.33
homepage: https://github.com/Enough-Software/enough_mail

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  pedantic: ^1.9.0
  event_bus: ^1.1.1
  intl: ^0.16.1
  crypto: ^2.1.4
  basic_utils: ^2.5.3
  xml: ">=3.6.1 <5.0.0"
  http: ^0.12.2



dev_dependencies:
  test: ^1.6.0
