name: enough_mail
description: IMAP, POP3 and SMTP email clients in pure Dart. Choose between a low level and a high level API for mailing.
version: 0.2.1
homepage: https://github.com/Enough-Software/enough_mail

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  pedantic: ^1.9.2
  event_bus: ^1.1.1
  intl: ^0.16.1
  crypto: ^2.1.5
  basic_utils: ^2.7.0
  xml: ^4.5.1
  http: ^0.12.2
  enough_serialization: ^1.2.0
    #path: ../enough_serialization
  enough_convert: ^0.10.0
    # path: ../enough_convert



dev_dependencies:
  test: ^1.15.4
