name: enough_mail
description: IMAP, POP3 and SMTP email clients in pure Dart. Choose between a low level and a high level API for mailing.
version: 0.0.33
homepage: https://github.com/Enough-Software/enough_mail

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  pedantic: ^1.9.2
  event_bus: ^1.1.1
  intl: ^0.16.1
  #crypto: ^2.1.5
  basic_utils: ^2.6.3
  xml: ^4.5.1
  http: ^0.12.2
  enough_serialization: any
    #path: ../enough_serialization



dev_dependencies:
  test: ^1.15.4
